NAME = filler

FLAGS = -Wall -Wextra -g -O3

LIB = libft/libft.a

SRCS =	filler.c		\
			read.c

BINS = $(SRCS:.c=.o)

all: $(NAME)

makelib:
	make -C libft/

libclean:
	make -C libft/ clean

libfclean:
	make -C libft/ fclean

$(NAME): $(BINS)
	make -C libft
	gcc -o $(NAME) $(BINS) $(FLAGS) $(LIB)

%.o: %.c
	gcc $(FLAGS) -c -o $@ $<

clean: libclean
	/bin/rm -f $(BINS)

fclean: libfclean clean
	/bin/rm -f $(NAME)

re: fclean all
